Setup BDJuno
oursky/likedao pull request #16
Opened 2022-04-29 05:42 UTC by hochiw

## Features 

- Setup BDJuno as a submodule for likedao
- Separated BDJuno database and graphql server database for local development
- Added bdjuno database to graphql server context
- Setup makefiles and docker-compose service for bdjuno
- Updated README.md

based on #15 
refs #3

2022-05-13 08:11 UTC, chihimng requested changes
can we have a quick demo on querying data from chain data db? say get the current sync progress?

2022-05-13 08:11 UTC, chihimng commented on graphql-server/pkg/mutators/test.go
>  }
no need to rename if this only concerns one db?

2022-05-13 08:11 UTC, chihimng commented on graphql-server/pkg/queries/test.go
> +	serverSession *bun.DB
no need to rename if this only concerns one db?

2022-05-13 08:11 UTC, chihimng commented on bdjuno/README.md
> +BDJuno is used as a crawler to synchonize in-chain data to a database
on-chain

2022-05-13 08:11 UTC, chihimng commented on bdjuno/Makefile
> +	git submodule update --init --recursive
👍

2022-05-13 08:39 UTC, hochiw commented
@chihimng Updated :adore2x:

2022-05-16 06:21 UTC, chihimng commented
@hochiw how about:

> can we have a quick demo on querying data from chain data db? say get the current sync progress?

2022-05-16 08:58 UTC, hochiw commented
@chihimng added a demo query for this

I have also temporarily locked the submodule to the latest commit in [aaron's dual prefix branch](https://github.com/forbole/bdjuno/commits/aaron/likecoin_dual_prefix) just so it doesn't crash when processing a block involving validator operations, or else it would never be able to catch up to latest blocks. Will open an issue to handle pointing the submodule to a stable build when it's available.

2022-05-16 09:36 UTC, chihimng approved these changes
👍

2022-05-16 10:27 UTC, merged