Implement reaction picker and reaction list
oursky/likedao pull request #162
Opened 2022-06-20 11:25 UTC by hochiw

refs #116

2022-06-23 09:28 UTC, hochiw commented
wait for #156 to merge before rebase

2022-06-26 18:47 UTC, chihimng commented
Plz add screenshot? 🙏

2022-06-26 19:08 UTC, chihimng requested changes
& plz help describe what was tested? like login on first auth error, and does the apollo cache work to reflect new action after mutation?

2022-06-26 19:08 UTC, chihimng commented on react-app/src/providers/AppApolloProvider.tsx
> +  const [isLogginIn, setIsLogginIn] = useState(false);
typo?

2022-06-26 19:08 UTC, chihimng commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreenAPI.ts
> +            targetId: `proposal_${proposalId}`,
client not supposed to format node ids... any easy way to accept node id instead?

2022-06-26 19:08 UTC, chihimng commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreenAPI.ts
> +export function useSetProposalReactionMutation(): (
can we have a generic set reaction api that accepts node id as input? & reuse it across whole app?

2022-06-26 19:08 UTC, chihimng commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreen.tsx
> +  const onSetReaction = useCallback(
can we refactor this to be reused for other reaction targets in the future?

2022-06-27 02:00 UTC, hochiw commented on react-app/src/components/reactions/ReactionPicker.tsx
> +              <span className={cn("text-3xl", "leading-none")}>{r.node}</span>
cos the size for the likecoin icon is different for the list and the picker

2022-06-27 02:02 UTC, hochiw commented on react-app/src/components/reactions/ReactionPicker.tsx
> +              <span className={cn("text-3xl", "leading-none")}>{r.node}</span>
unless i separate it into `pickerNode` and `listNode`

2022-06-27 09:55 UTC, hochiw commented on react-app/src/components/reactions/ReactionPicker.tsx
> +              <span className={cn("text-3xl", "leading-none")}>{r.node}</span>
resolved with css

2022-06-27 10:09 UTC, hochiw commented
@chihimng updated 🙏

2022-06-28 11:47 UTC, chihimng approved these changes

2022-06-28 11:48 UTC, merged