Setup deployment
oursky/likedao pull request #17
Opened 2022-05-10 15:37 UTC by hochiw

- Setup helm chart
- Created deployment templates and configs for react app, bdjuno and graphql server
- Added makefile for easier access to deployment commands
- Updated README.md on deployment information

- Tested by deploying onto oursky k8s 

based on #16
refs #11

2022-05-13 08:54 UTC, chihimng requested changes

2022-05-13 08:54 UTC, chihimng commented on deploy/likedao/templates/NOTES.txt
> -1. Get the application URL by running these commands:
please fixup this commit?

2022-05-13 08:54 UTC, chihimng commented on deploy/Makefile
> +ENV ?=
is this used?

2022-05-13 08:54 UTC, chihimng commented on deploy/likedao/.gitignore
> +static/react-app.nginx.
missing conf extension?

2022-05-13 08:54 UTC, chihimng commented on deploy/likedao/values.sample.yaml
> +  imageName: gcr.io/oursky-kube/likedao/likedao-graphql-server
ghcr?

2022-05-13 08:54 UTC, chihimng commented on deploy/likedao/.gitignore
> +static/react-app.nginx.conf
please fixup commit next time

2022-05-16 10:30 UTC, chihimng commented
plz rebase 🙏

2022-05-16 10:44 UTC, hochiw commented
@chihimng updated :adore2x:

2022-05-17 08:21 UTC, chihimng approved these changes

2022-05-17 08:21 UTC, chihimng commented on README.md
> +
how about specs for db & steps to seed the initial schema?

2022-05-17 08:21 UTC, chihimng commented
@hochiw code lgtm, see if you want to handle docs now or track with issue

2022-05-17 08:26 UTC, hochiw commented
Added an issue for this https://github.com/oursky/likedao/issues/39

2022-05-17 09:41 UTC, merged