Implement governance params API
oursky/likedao pull request #173
Opened 2022-06-21 08:01 UTC by ivanng-oursky

### Changes

- Implemented graphql schema, server models, query and resolvers for gov_params

#### Request
```gql
query GovParms {
  getGovParams {
  	__typename
    depositParams {
      __typename
      minDeposit {
        __typename
        denom
        amount
      }
      maxDepositPeriod
    }
    votingParams {
      __typename
      votingPeriod
    }
    tallyParams {
      __typename
      quorum
      threshold
      vetoThreshold
    }
  }
}
```

#### Response (TestNet)
```json
{
  "data": {
    "getGovParams": {
      "__typename": "GovParams",
      "depositParams": {
        "__typename": "DepositParams",
        "minDeposit": [
          {
            "__typename": "Coin",
            "denom": "nanoekil",
            "amount": "10000000"
          }
        ],
        "maxDepositPeriod": 86400000000000
      },
      "votingParams": {
        "__typename": "VotingParams",
        "votingPeriod": 86400000000000
      },
      "tallyParams": {
        "__typename": "TallyParams",
        "quorum": "0.334000000000000000",
        "threshold": "0.500000000000000000",
        "vetoThreshold": "0.334000000000000000"
      }
    }
  }
}
```

2022-06-22 11:38 UTC, hochiw requested changes

2022-06-22 11:38 UTC, hochiw commented on graphql-server/pkg/queries/gov.go
> +	err := q.session.NewSelect().Model(govParams).Where("one_row_id = true").Scan(q.ctx)
Probably we don't need this where filter?

2022-06-22 11:38 UTC, hochiw commented on graphql-server/pkg/models/gov.go
> +	OneRowID      bool          `bun:"column:one_row_id"`
Probably no need this

2022-06-23 03:20 UTC, ivanng-oursky commented
@hochiw updated 🙇

2022-06-23 06:15 UTC, hochiw approved these changes

2022-06-23 06:15 UTC, merged