Implement TallyResultIndicator
oursky/likedao pull request #179
Opened 2022-06-22 06:14 UTC by hochiw

- Updated colorBar component to handle custom height with percentage display
- Implemented TallyResultIndicator with use case at ProposalDetail data section

## Screenshots 

| Desktop | Mobile |
|---------|---------|
|<img width="1571" alt="Screenshot 2022-06-22 at 2 07 27 PM" src="https://user-images.githubusercontent.com/18374475/174956468-f85959d2-c4f2-4c7e-9fbc-2564c06c7599.png">|<img width="494" alt="Screenshot 2022-06-22 at 2 07 34 PM" src="https://user-images.githubusercontent.com/18374475/174956501-b978af5f-cc00-4cd1-a3c7-2fbd16a7fb48.png">|

refs #126

2022-06-22 17:20 UTC, chihimng requested changes
one question on responsive / small percentage sections

2022-06-22 17:20 UTC, chihimng commented on react-app/src/components/common/ColorBar/ColorBar.tsx
> +  useEffect(() => {
do we need something like `useWindowSize`?

2022-06-22 17:20 UTC, chihimng commented on react-app/src/components/common/ColorBar/ColorBar.tsx
> +  useEffect(() => {
how did we handle small percentage sections at the end?

2022-06-23 09:29 UTC, hochiw commented
@chihimng updated 🙏

2022-06-26 19:14 UTC, chihimng approved these changes

2022-06-27 06:08 UTC, merged