Fix proposal detail page various bugs
oursky/likedao pull request #232
Opened 2022-07-07 11:11 UTC by ivanng-oursky

- remaining voting days should be difference in calendar days (if <24hrs remaining, count as one day)
- deposit total needs to be converted from minimal token to token
- don't show zero when value of remaining voting days is zero
- link proposer, voter and depositor to their respective portfolio page

<img width="977" alt="image" src="https://user-images.githubusercontent.com/106721852/177755946-b8c73160-84ff-4878-9414-f35c1ecd0b2c.png">

2022-07-08 09:29 UTC, ivanng-oursky commented
@hochiw will fix the proposal list change tab wrong page number issue in this PR too.

2022-07-12 04:17 UTC, hochiw requested changes

2022-07-12 04:17 UTC, hochiw commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreenAPI.ts
> +        );
debug log

2022-07-12 04:17 UTC, hochiw commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreenAPI.ts
> +            }),
Let's create a map in LocaleProvider for this, as we don't know whether there will be more languages in the future

2022-07-12 04:17 UTC, hochiw commented on react-app/src/components/ProposalDetailScreen/ProposalHeader.tsx
> +  const [name, setName] = useState<string>();
vague naming, what name?

2022-07-12 06:01 UTC, ivanng-oursky commented
@hochiw updated

2022-07-13 07:57 UTC, hochiw approved these changes

2022-07-13 07:57 UTC, merged