Prevent page reloading when prompting user authentication
oursky/likedao pull request #264
Opened 2022-07-13 09:32 UTC by hochiw

- Convert authErrorLink handling to useRef

refs #221

2022-07-14 06:30 UTC, chihimng approved these changes

2022-07-14 07:10 UTC, chihimng commented
actually, would the correct fix be using ref for `auth, isLoggingIn` in authErrorLink?

2022-07-14 07:12 UTC, chihimng requested changes
see above

2022-07-15 04:00 UTC, hochiw commented
@chihimng updated 🙏

2022-07-15 07:16 UTC, chihimng approved these changes

2022-07-15 08:28 UTC, merged