Handle gql bigint type using string
oursky/likedao pull request #266
Opened 2022-07-13 10:19 UTC by hochiw

- Implemented custom BigInt and BigFloat type for gql
- Removed gql_big-int package

<img width="1386" alt="Screenshot 2022-07-13 at 6 17 39 PM" src="https://user-images.githubusercontent.com/18374475/178711233-d09efdf4-b5a7-4e49-8ec6-a08e9a8937ff.png">

refs #246

2022-07-14 07:16 UTC, chihimng requested changes

2022-07-14 07:16 UTC, chihimng commented on graphql-server/pkg/resolvers/proposal.go
> +	return models.BigInt(obj.Abstain.String()), nil
can we have a constructor to make value from bun.bigint?

2022-07-14 07:16 UTC, chihimng commented on graphql-server/pkg/resolvers/proposal.go
> +		return "0", nil
& with a custom constructor, i prefer models.BigInt(0) here for readability

2022-07-15 04:26 UTC, hochiw commented
@chihimng updated :pray:

2022-07-15 07:28 UTC, chihimng approved these changes

2022-07-15 08:28 UTC, merged