Create validator detail panel
oursky/likedao pull request #267
Opened 2022-07-13 10:52 UTC by ivanng-oursky

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/106721852/178716880-8e13ae00-b1a8-47f3-8200-3c08a4a164ab.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/106721852/178716918-ef22951f-5161-45f7-b7e5-654d8e790ecc.png">

refs #238

2022-07-15 07:02 UTC, hochiw requested changes
<img width="1077" alt="Screenshot 2022-07-15 at 2 55 31 PM" src="https://user-images.githubusercontent.com/18374475/179168661-7e77a7e9-12d2-4677-9370-29a75a85d65a.png">

Seems to be a new button size, and different colour for the unstake button?

<img width="394" alt="Screenshot 2022-07-15 at 2 56 54 PM" src="https://user-images.githubusercontent.com/18374475/179168884-97b2eb87-037c-4825-9659-9ff0214f7ecb.png">

may need `justify-between` for APY container?

<img width="314" alt="Screenshot 2022-07-15 at 2 58 26 PM" src="https://user-images.githubusercontent.com/18374475/179169149-55e5f295-3b4a-4f2a-8917-7de422be8c42.png">

seems the spacing between the url and bonded tokens should be 24 (mb-6)?

<img width="208" alt="Screenshot 2022-07-15 at 2 59 54 PM" src="https://user-images.githubusercontent.com/18374475/179169423-a70c0eee-9055-46fd-b6e0-b69fc14da8a2.png">

logo becomes rectangle as I shrink the window

2022-07-15 10:09 UTC, ivanng-oursky commented
@hochiw updated

https://user-images.githubusercontent.com/106721852/179202516-a3554950-8b65-449e-9210-b9df33ed74d4.mov

2022-07-15 11:12 UTC, hochiw requested changes

2022-07-15 11:12 UTC, hochiw commented on react-app/src/components/common/Buttons/AppButton.tsx
> +        size === "regular" ? cn("py-3", "px-6") : null,
Seems very shared, should we keep the switch case function?

2022-07-18 03:23 UTC, ivanng-oursky commented
@hochiw updated 🙇

2022-07-18 04:33 UTC, hochiw requested changes

2022-07-18 04:33 UTC, hochiw commented on react-app/src/components/common/Buttons/AppButton.tsx
> +        size === "regular" ? cn("py-3", "px-6") : null,
getButtonPaddings?

2022-07-18 04:33 UTC, hochiw commented on react-app/src/components/common/Buttons/AppButton.tsx
> +          // getButtonSizeStyle(size),
remove if not used

2022-07-18 06:40 UTC, ivanng-oursky commented
@hochiw updated

2022-07-18 06:42 UTC, hochiw approved these changes

2022-07-18 06:42 UTC, merged