Persist walletconnect connection
oursky/likedao pull request #273
Opened 2022-07-14 06:01 UTC by hochiw

- Store walletconnect user information in local storage
- Handle auto reconnect wallet connect
- Moved user balance that is used for display to walletprovider

refs #272

2022-07-14 08:01 UTC, chihimng requested changes

2022-07-14 08:01 UTC, chihimng commented on react-app/src/clients/walletConnectClient.ts
> +        `${WALLET_CONNECT_PEER_ID}-${connector.peerId}`
can we make an util func for obtaining LS key from peer id?

2022-07-14 11:26 UTC, hochiw commented
Autoconnect also logs out now, will fix in this PR

2022-07-15 04:43 UTC, hochiw commented
> Autoconnect also logs out now, will fix in this PR

Actually it's possible for it to be different accounts even when it's connected automatically, maybe think about this later

2022-07-15 04:46 UTC, hochiw commented
@chihimng updated 🙏

2022-07-15 07:29 UTC, chihimng approved these changes

2022-07-15 08:33 UTC, merged