Fetch quorum param from rpc for proposal detail
oursky/likedao pull request #276
Opened 2022-07-14 07:05 UTC by hochiw

- Implemented getGovParamsAPI in proposal detail API 
- Handle quorum display in ProposalVotesPanel
- Replace hardcoded toast messages in ProposalDetail with i18n messages

<img width="919" alt="Screenshot 2022-07-14 at 3 03 00 PM" src="https://user-images.githubusercontent.com/18374475/178922080-ab25eabf-31a9-4fc2-8e53-8f67742d0a9e.png">
<img width="410" alt="Screenshot 2022-07-14 at 3 03 14 PM" src="https://user-images.githubusercontent.com/18374475/178922101-a1158cc3-11de-45ee-b74f-b0ea12490ad4.png">

refs #245

2022-07-14 08:07 UTC, chihimng requested changes

2022-07-14 08:07 UTC, chihimng commented on react-app/src/components/ProposalDetailScreen/ProposalDetailScreenAPI.ts
> +        throw err;
should still set request state error here with a custom error of "unknown error"? and maybe log to console?

2022-07-18 06:48 UTC, hochiw commented
@chihimng updated :adore2x:

2022-07-18 06:50 UTC, chihimng approved these changes

2022-07-19 06:48 UTC, merged