Update footer urls and rename Likecoin to LikeCoin
oursky/likedao pull request #348
Opened 2022-07-29 04:32 UTC by hochiw

- Renamed all Likecoin usage to LikeCoin
- Added github url to footer and change license text
- Updated osmosis url
- Removed liquid and emeris url

| Desktop | Mobile |
|---------|--------|
|<img width="1348" alt="Screenshot 2022-07-29 at 12 31 19 PM" src="https://user-images.githubusercontent.com/18374475/181683249-332ed7d2-5a13-4e85-b1ea-58a14f773e2f.png">|<img width="437" alt="Screenshot 2022-07-29 at 12 31 25 PM" src="https://user-images.githubusercontent.com/18374475/181683258-59583a85-14e7-49d1-92f2-912435927fe2.png">|

refs #327 #328

2022-07-29 06:01 UTC, chihimng requested changes

2022-07-29 06:01 UTC, chihimng commented on react-app/src/providers/AuthProvider.tsx
> +    `${url.host} wants you to sign in with your LikeCoin account:\n` +
need to update backend?

2022-08-01 07:09 UTC, hochiw commented
@chihimng  Updated and tested

2022-08-01 07:13 UTC, chihimng approved these changes

2022-08-01 07:32 UTC, merged