Store locale preference
oursky/likedao pull request #36
Opened 2022-05-16 10:54 UTC by hochiw

- Introduced useLocalStorage hook
- Added context to appLocaleProvider for locale setting
- Parse local storage for locale preference 
- Added a dummy button in HomePage for switching locale

refs #18

2022-05-17 09:39 UTC, chihimng requested changes

2022-05-17 09:39 UTC, chihimng commented on react-app/src/i18n/translations/zh.json
> +  "App.title": "你好世界"
:sosad:

2022-05-17 09:39 UTC, chihimng commented on react-app/src/providers/AppLocaleProvider.tsx
> +  const [appLocale, setAppLocale] = useState<Locale>(localePref ?? Locale.en);
keeping two states looks a little weird to me 🤔

2022-05-17 09:39 UTC, chihimng commented on react-app/src/providers/AppLocaleProvider.tsx
> +    return Translations[appLocale];
hypothetically, a user can edit the local storage values in developer menu and cause error here? should we sanitize the value?

2022-05-17 09:39 UTC, chihimng commented on react-app/src/providers/AppLocaleProvider.tsx
> +  const [appLocale, setAppLocale] = useState<Locale>(localePref ?? Locale.en);
should we handle default value fallback at the useMemo instead? (along with checking if the local is valid, see below)

2022-05-17 09:39 UTC, chihimng commented on react-app/src/components/HomeScreen/HomeScreen.tsx
> +  const setLocale = useCallback(
onClick callback should handle React.MouseEvent...
please refactor the button component?

2022-05-19 06:45 UTC, hochiw commented
@chihimng updated 🙏

2022-05-19 08:13 UTC, chihimng approved these changes

2022-05-19 08:29 UTC, merged