Adapt global gql identification system
oursky/likedao pull request #38
Opened 2022-05-16 12:58 UTC by hochiw

- Implemented standard node id interface
- Specify Block and Test object ID as NodeID
- Updated createTest mutation to return whole object

refs #29

2022-05-19 08:55 UTC, chihimng commented
@hochiw please help introduce Node and PageInfo base type, and extend Node type: https://relay.dev/docs/guides/graphql-server-specification/

2022-05-19 10:04 UTC, hochiw commented
@chihimng updated 🙏

2022-05-19 11:06 UTC, chihimng requested changes

2022-05-19 11:06 UTC, chihimng commented on graphql-server/pkg/utils/node_id.go
> +func MarshalNodeID(nodeID models.NodeID) graphql.Marshaler {
move to model file?

2022-05-19 11:06 UTC, chihimng commented on graphql-server/gqlgen.yml
> +    model: github.com/oursky/likedao/pkg/utils.NodeID
models.NodeID?

2022-05-19 11:06 UTC, chihimng commented on graphql-server/pkg/resolvers/test.go
> +	for _, id := range ids {
refactor to helper for reuse in the future?

map []NodeID to []string

2022-05-19 16:12 UTC, hochiw commented
@chihimng updated :adore2x:

2022-05-20 08:12 UTC, chihimng commented
@hochiw got extra commit again :sadfrog:

2022-05-20 08:14 UTC, hochiw commented
> @hochiw got extra commit again :sadfrog:

removed

2022-05-20 08:29 UTC, chihimng requested changes

2022-05-20 08:29 UTC, chihimng commented on graphql-server/pkg/models/node_id.go
> +			gqlerrcode.Set(gqlerr, "VALIDATION_FAILED")
can this error code be refactored?

2022-05-20 08:29 UTC, chihimng commented on graphql-server/pkg/models/node.go
> +type NodeID struct {
can `node.go` and `node_id.go` be combined? seems both are about NodeID

2022-05-20 08:29 UTC, chihimng commented on graphql-server/pkg/resolvers/relay.go
> +	case "test":
how about block?

2022-05-23 05:39 UTC, hochiw commented on graphql-server/pkg/resolvers/relay.go
> +	case "test":
Added a query

2022-05-23 07:26 UTC, hochiw commented
@chihimng updated :adore2x:

2022-05-23 08:32 UTC, chihimng commented on graphql-server/pkg/resolvers/block.go
> +	res, err := pkgContext.GetQueriesFromCtx(ctx).Block.QueryBlockByHash(hash.ID)
https://github.com/oursky/likedao/issues/52

2022-05-23 08:32 UTC, chihimng approved these changes

2022-05-23 08:33 UTC, merged