Implement Overview page and sidebar component
oursky/likedao pull request #40
Opened 2022-05-18 04:40 UTC by hochiw

refs #33

2022-05-19 11:11 UTC, chihimng commented
plz align mobile margin with design

2022-05-19 11:14 UTC, hochiw commented on react-app/src/components/OverviewScreen/OverviewScreen.tsx
> +      </WithSideBar>
should handle using router

2022-05-20 09:17 UTC, chihimng commented
@hochiw ui nitpick on mobile:

- best to have bottom padding for the button list / menu in case scroll is needed:

![image](https://user-images.githubusercontent.com/11769136/169496773-e50ea7c0-b312-40c3-881b-39494daa799d.png)

- on click current tab, should dismiss the menu on mobile?

2022-05-20 09:31 UTC, chihimng requested changes

2022-05-23 06:21 UTC, hochiw commented on react-app/src/components/AppSideBar/AppSideBar.tsx
> +        "bg-gradient-to-b",
this?

<img width="236" alt="Screenshot 2022-05-23 at 2 18 42 PM" src="https://user-images.githubusercontent.com/18374475/169755993-6d878486-15ae-4af4-bcf2-e25df4eca937.png">

2022-05-23 06:21 UTC, hochiw commented on react-app/src/components/AppSideBar/AppSideBar.tsx
> +        "bg-gradient-to-b",
from the most outer component for overview page in figma

2022-05-23 07:26 UTC, hochiw commented
@chihimng updated :adore2x:

2022-05-23 08:33 UTC, chihimng commented on react-app/src/components/AppSideBar/AppSideBar.tsx
> +        "bg-gradient-to-b",
not noticing this on screen @.@

2022-05-23 08:39 UTC, chihimng approved these changes

2022-05-23 08:39 UTC, merged