Implement community status component
oursky/likedao pull request #62
Opened 2022-05-25 11:22 UTC by hochiw

## Features
- Implemented regular and header type community status component
- Added reuglar community status to overview screen

## Pending
- Loading and error state for overview screen

## Screenshots

| Desktop | Mobile |
|---------|--------|
|<img width="1859" alt="Screenshot 2022-05-25 at 7 18 10 PM" src="https://user-images.githubusercontent.com/18374475/170250739-6355a106-8b6e-4a9e-931a-652ef0cd31b4.png">|<img width="376" alt="Screenshot 2022-05-25 at 7 18 20 PM" src="https://user-images.githubusercontent.com/18374475/170250764-410398b0-c0a2-4e5b-8884-7958b5a229a7.png">|
|<img width="1863" alt="Screenshot 2022-05-25 at 7 19 35 PM" src="https://user-images.githubusercontent.com/18374475/170250768-12726dcb-8ac9-4ef4-be66-da6508ec3e92.png">| - |

based on #59  #61 
refs #50

2022-05-27 03:25 UTC, chihimng commented
any update on the design question for humanizing big numbers?

2022-05-27 03:27 UTC, hochiw commented
> any update on the design question for humanizing big numbers?

yes designer agreed on using 10M, 10B with a minified version of the full number at the bottom, i will update later

2022-05-30 18:21 UTC, chihimng requested changes

2022-05-30 18:21 UTC, chihimng commented on react-app/src/components/OverviewScreen/OverviewScreen.graphql
> +query LatestCommunityStatus {
This should be OverviewScreenQuery?

And we should have a OverviewScreenAPI.ts?

Can we also introduce RequestState?

2022-05-30 18:21 UTC, chihimng commented on react-app/src/components/CommunityStatus/CommunityStatusRegular.tsx
> +    // Return normal value if communityPool is less than a million
Refactor this to a util?

2022-05-31 11:17 UTC, chihimng commented
plz rebase

2022-05-31 14:13 UTC, hochiw commented
@chihimng updated :adore2x:

2022-06-02 01:48 UTC, chihimng approved these changes

2022-06-02 01:48 UTC, chihimng commented on react-app/src/components/OverviewScreen/OverviewScreen.graphql
> +query OverviewScreenQueryCommunityStatus {
we can name this `OverviewScreenQuery`? if there is anything extra needed we will combine in one query anyways?

2022-06-02 01:48 UTC, chihimng commented on react-app/src/components/OverviewScreen/OverviewScreen.graphql
> +query OverviewScreenQueryCommunityStatus {
can rename later

2022-06-02 02:12 UTC, chihimng requested changes

2022-06-02 02:12 UTC, chihimng commented on react-app/src/utils/number.ts
> +export function convertToReadableNumber(
can these be named more straight forward? a bit hard to guess which does what

2022-06-02 03:19 UTC, hochiw commented
@chihimng updated :adore2x:

2022-06-02 03:29 UTC, chihimng approved these changes

2022-06-02 03:30 UTC, merged