Create dataloader for block
oursky/likedao pull request #63
Opened 2022-05-26 06:33 UTC by hochiw

## Features
- Unify query names to use ID
- Created batch query for block object
- Create batch graphql query for block object 

refs #52

2022-05-30 18:36 UTC, chihimng requested changes

2022-05-30 18:36 UTC, chihimng commented on graphql-server/pkg/resolvers/block.go
> +	res, errs := pkgContext.GetDataLoadersFromCtx(ctx).Block.LoadAll(blockHashes)
adopt this at `BlockByID` resolver as well?

2022-05-31 12:13 UTC, hochiw commented
@chihimng updated :adore2x:

2022-05-31 12:17 UTC, chihimng approved these changes

2022-05-31 12:17 UTC, merged