Handle Proposal Listing
oursky/likedao pull request #99
Opened 2022-06-08 18:04 UTC by hochiw

## Features
- Added proposalID and mostVoted to proposal object in schema and handled resolving on gql server
- Implemented gql schema and api for proposal screen
- Fixed BigInt and BigFloat scalar link not parsing values correctly and adapts new BigInt type from gql server
- Implemented ColorBar component
- Implemented ProposalCard
- Integrated ProposalCard to the proposal list in ProposalScreen with real data

Note: Will handle pagination and filtering in another PR otherwise it'd be too big

## Pending
- error handling for all screens(TBC)
- empty state

## Screenshots
| Desktop | Mobile |
|---------|--------|
|<img width="1405" alt="Screenshot 2022-06-09 at 5 46 46 PM" src="https://user-images.githubusercontent.com/18374475/172818805-2cdd48cf-61d0-4864-abbf-904875c0166d.png">|<img width="292" alt="Screenshot 2022-06-09 at 5 47 05 PM" src="https://user-images.githubusercontent.com/18374475/172818822-c8d7578a-74c6-4333-ad63-dfbe9cfcd8d6.png">|

based on partial #92 
refs #69

2022-06-09 09:00 UTC, chihimng requested changes

2022-06-09 09:03 UTC, chihimng commented
the new proposal & view details button text seems deviated from design?

2022-06-09 09:12 UTC, hochiw commented
> the new proposal & view details button text seems deviated from design?

oops old screenshot, will update

2022-06-09 09:16 UTC, hochiw commented on react-app/src/components/ProposalScreen/ProposalList.tsx
> +    <div className={cn("flex", "flex-col", "gap-y-16")}>
it's not supported by third world browsers as of now, do we need to cater?

![圖片](https://user-images.githubusercontent.com/18374475/172811772-b1f86c0f-8ff2-4e09-803b-868f91bb019d.png)

2022-06-09 09:19 UTC, chihimng commented on react-app/src/components/ProposalScreen/ProposalList.tsx
> +    <div className={cn("flex", "flex-col", "gap-y-16")}>
i guess ok then 🤔

2022-06-09 09:38 UTC, hochiw commented on graphql-schema/proposal.graphql
> +  mostVoted: ProposalVoteOption
in fact the whole tally result should be nullable when the voting period is not reached

2022-06-09 09:54 UTC, hochiw commented on react-app/src/components/common/DateTime/UTCDatetime.tsx
> +      {format(date.toISOString().slice(0, -1), "YYYY-MM-DD HH:mm")} UTC
UTC is expected, and seems like date-fns would convert to local time automatically, maybe we'll need to use `date-fns-tz` for the conversion

2022-06-09 09:56 UTC, chihimng commented on react-app/src/components/common/DateTime/UTCDatetime.tsx
> +      {format(date.toISOString().slice(0, -1), "YYYY-MM-DD HH:mm")} UTC
i prefer offloading to library instead of manually tinkering with the iso string

2022-06-09 10:00 UTC, chihimng commented on react-app/src/components/common/DateTime/UTCDatetime.tsx
> +      {format(date.toISOString().slice(0, -1), "YYYY-MM-DD HH:mm")} UTC
side note, for ux i think best to add a duration display? (in x days / hours)

2022-06-09 12:13 UTC, hochiw commented on react-app/src/components/common/DateTime/UTCDatetime.tsx
> +      {format(date.toISOString().slice(0, -1), "YYYY-MM-DD HH:mm")} UTC
The detail page has it, and we might not have enough space for that on mobile🤔

2022-06-10 04:08 UTC, hochiw commented
@chihimng updated

2022-06-11 13:31 UTC, chihimng approved these changes

2022-06-11 13:46 UTC, merged